export const Constants = {
  //URLS
  GOOGLE_PAY_URL: "https://pay.google.com/gp/p/js/pay.js",
  IP_ADDRESS_URL: 'https://api.ipify.org?format=json',
  // PAYPAL_CHECKOUT_URL :"https://www.paypal.com/en_US/i/btn/btn_xpressCheckout.gif",//todo:paypal
  PAYPAL_CHECKOUT_URL: "https://www.paypalobjects.com/webstatic/en_AU/i/buttons/btn_paywith_primary_l.png",
  //TEST URLS
  TEST_VISA_CHECKOUT_URL:
    "https://sandbox-assets.secure.checkout.visa.com/checkout-widget/resources/js/integration/v1/sdk.js",
  TEST_DEVICE_DATA_COLLECTION_URL: "https://centinelapistag.cardinalcommerce.com",
  TEST_VISA_BUTTON_URL: "https://sandbox.secure.checkout.visa.com/wallet-services-web/xo/button.png",
  TEST_PAYPAL_URL: "https://www.paypal.com/sdk/js",//todo:payao
  // TEST_PAYPAL_URL:"https://www.paypalobjects.com/sdk/js",
  DEVICE_FINGERPRINT_URL_TEST: "https://h.online-metrix.net/fp/tags.js?org_id=1snn5n9ww&session_id=",
  //PRODUCTION URLS
  PRODUCTION_VISA_CHECKOUT_URL:
    "https://assets.secure.checkout.visa.com/checkout-widget/resources/js/integration/v1/sdk.js",
  PRODUCTION_DEVICE_DATA_COLLECTION_URL: "https://centinelapi.cardinalcommerce.com",
  PRODUCTION_VISA_BUTTON_URL: "https://secure.checkout.visa.com/wallet-services-web/xo/button.png",
  APPLE_PAY_SUPPORTED_NETWORKS: ["amex", "masterCard", "visa"],
  APPLE_PAY_MERCHANT_CAPABILITIES: ["supports3DS", "supportsEMV", "supportsCredit", "supportsDebit"],
  ISV_PAYMENT_VUE: "./IsvPayment/IsvPayment.vue",
  DEVICE_FINGERPRINT_URL_LIVE: "https://h.online-metrix.net/fp/tags.js?org_id=k8vif92e&session_id=",
  //RUN ENVIRONMENT
  ISV_PAYMENT_ENVIRONMENT_TEST: "TEST",
  ISV_PAYMENT_ENVIRONMENT_PRODUCTION: "PRODUCTION",
  //STRINGS
  PAYMENT_INTERFACE: "cybersource",
  PAYMENT_INTERFACE_TYPE: "isv_payment_data",
  STRING_ADD_ADDRESS: "addAddress",
  STRING_ADDRESSES: "addresses",
  STRING_CHOOSE: "choose",
  STRING_CARD: 'card',
  STRING_CUSTOM: "custom",
  STRING_CUSTOMER_ID: "customer_id",
  STRING_DATA_ERASURE: "dataErasure",
  STRING_DELETE: "delete",
  STRING_ERRORS: "errors",
  STRING_FIELDS: "fields",
  STRING_FLAG: "flag",
  STRING_LONG: "long",
  STRING_MULTIPLE: "Multiple",
  STRING_NUMBER: "number",
  STRING_SRC: "src",
  STRING_INTEGRITY : "integrity",
  STRING_CROSS_ORIGIN : "crossorigin",
  STRING_ANONYMOUS : "anonymous",
  STRING_SCRIPT: "script",
  STRING_SET_PAYMENT: "setPayment",
  STRING_SECURITY_CODE: "securityCode",
  STRING_TRUE: "true",
  STRING_FALSE: "false",
  STRING_TYPE: "type",
  STRING_UPDATE: "update",
  STRING_UPDATED: "updated",
  STRING_UN_ES: "en-us",
  STRING_VALIDATION_CALLBACK: "validationCallback",
  STRING_VERSION: "version",
  //language
  STRING_EN_US: "en-US",
  STRING_DE_DE: "de-DE",
  STRING_EN: "en",
  STRING_DE: "de",
  STRING_LOCALE: "locale",
  //Number, Regex
  COLON: ":",
  EMPTY_STRING: "",
  WHITESPACE: " ",
  FLOAT_ZERO: 0.0,
  NUMBER_ZERO: 0,
  NUMBER_ONE: 1,
  NUMBER_TWO: 2,
  NUMBER_NINE: 9,
  NUMBER_TWELVE: 12,
  NUMBER_HUNDRED: 100,
  NUMBER_FIVE_ZERO_FOUR: 504,
  NUMBER_FIVE_ZERO_TWO: 502,
  //Payment info
  ALLOWED_CARD_AUTH_METHODS: ["PAN_ONLY", "CRYPTOGRAM_3DS"],
  ALLOWED_CARD_NETWORKS: ["AMEX", "DISCOVER", "INTERAC", "JCB", "MASTERCARD", "VISA"],
  CARD: 'CARD',
  GATEWAY_NAME: 'cybersource',
  GOOGLE_PAY_API_VERSION: 2,
  GOOGLE_PAY_API_VERSION_MINOR: 0,
  GOOGLE_PAY_CALLBACK_INTENTS: ["PAYMENT_AUTHORIZATION"],
  GOOGLE_PAY_ERROR: 'ERROR',
  GOOGLE_PAY_ERROR_MESSAGE: 'Unable to pay using Google Pay',
  GOOGLE_PAY_INTENT: 'PAYMENT_AUTHORIZATION',
  GOOGLE_PAY_INSUFFICIENT_FUNDS: 'Insufficient funds',
  GOOGLE_PAY_PAYMENT_DATA_INVALID: 'PAYMENT_DATA_INVALID',
  GOOGLE_PAY_TOTAL_LABEL: 'Total',
  GOOGLE_PAY_TOTAL_PRICE_STATUS_UNKNOWN: 'NOT_CURRENTLY_KNOWN',
  GOOGLE_PAY_TOTAL_PRICE_STATUS: 'FINAL',
  GOOGLE_PAY_SUCCESS: 'SUCCESS',
  PAYMENT_GATEWAY: 'PAYMENT_GATEWAY',
  HTTP_METHOD_GET: "GET",
  HTTP_METHOD_POST: "POST",
  //Payment methods
  APPLE_PAY: "applePay",
  CREDIT_CARD: "creditCard",
  PAYPAL: "payPal",//TODO:PAYPAL
  PAYPAL_EN: "PayPal",
  CC_WITH_PAYER_AUTH: "creditCardWithPayerAuthentication",
  ECHECK: "eCheck",
  FLEX_MICROFORM: "flexMicroform",
  GOOGLE_PAY: "googlePay",
  VISA_CHECKOUT: "clickToPay",
  UNIFIED_CHECKOUT: "unifiedCheckout",
  APPLE_PAY_EN: "Apple Pay",
  CREDIT_CARD_EN: "Credit Card",
  CC_WITH_PAYER_AUTH_EN: "Credit Card Payer Authentication",
  GOOGLE_PAY_EN: "Google Pay",
  VISA_CHECKOUT_EN: "Click to Pay",
  //CT fields
  ISV_ACCEPT_HEADER: "isv_acceptHeader",
  ISV_ACCEPT_HEADER_VALUE: "*/*",
  ISV_ADDRESS_ID: "isv_addressId",
  ISV_CARD_EXPIRY_MONTH: "isv_cardExpiryMonth",
  ISV_CARD_EXPIRY_YEAR: "isv_cardExpiryYear",
  ISV_CARD_NEW_EXPIRY_MONTH: "isv_cardNewExpiryMonth",
  ISV_CARD_NEW_EXPIRY_YEAR: "isv_cardNewExpiryYear",
  ISV_CARD_TYPE: "isv_cardType",
  ISV_CURRENCY_CODE: "isv_currencyCode",
  ISV_CUSTOMER_IP_ADDRESS: "isv_customerIpAddress",
  ISV_DDC_URL: 'isv_deviceDataCollectionUrl',
  ISV_DEVICE_FINGERPRINT_ID: "isv_deviceFingerprintId",
  ISV_FAILED_TOKENS: "isv_failedTokens",
  ISV_MASKED_PAN: "isv_maskedPan",
  ISV_PAYMENT_APPLE_PAY_SESSION_DATA: "isv_applePaySessionData",
  ISV_PAYER_AUTHENTICATION_REQUIRED: "isv_payerAuthenticationRequired",
  ISV_PAYER_AUTHENTICATION_TRANSACTION_ID: "isv_payerAuthenticationTransactionId",
  ISV_PAYMENTS_CUSTOMER_TOKENS: "isv_payments_customer_tokens",
  ISV_REQUEST_JWT: "isv_requestJwt",
  ISV_RESPONSE_JWT: "isv_responseJwt",
  ISV_SAVED_TOKEN: "isv_savedToken",
  ISV_STEPUP_URL: 'isv_stepUpUrl',
  ISV_TOKEN: "isv_token",
  ISV_TOKENS: "isv_tokens",
  ISV_TOKEN_ACTION: "isv_tokenAction",
  ISV_TOKEN_ALIAS: "isv_tokenAlias",
  ISV_TOKEN_CAPTURE_CONTEXT: "isv_tokenCaptureContextSignature",
  ISV_USER_AGENT_HEADER: "isv_userAgentHeader",
  ISV_SALE_ENABLED: "isv_saleEnabled",
  PLACEHOLDER_ENTER_CARD_NO: "Enter card number",
  PLACEHOLDER_3DOTS: "•••",
  //Error messages
  ERROR_MSG_APPLE_PAY_NOT_ACTIVATED: "Apple Pay is possible on this browser, but currently not activated.",
  ERROR_MSG_APPLE_PAY_NOT_SUPPORTED: "Apple Pay is not available on this browser.",
  ERROR_MSG_APPLE_PAY_SESSION: "There was an error establishing a apple pay session.",
  ERROR_MSG_DELETE_TOKEN: "Card deletion failed. Please try again.",
  ERROR_MSG_GOOGLE_PAY: 'Unable to pay using Google Pay.',
  ERROR_MSG_GOOGLE_PAY_LOADING: 'Error in loading Google Pay.',
  ERROR_MSG_FIVE_ZERO_TWO: "There was a server error, please try again.",
  ERROR_MSG_FILL_REQUIRED_DATA: "* Please fill in all required data",
  ERROR_MSG_FIVE_ZERO_FOUR: "Unable to process your request, please try again.",
  ERROR_MSG_FORM_LOAD: "Unable to load the form, try again.",
  ERROR_MSG_INVALID_EXPIRY_DATE: "Selected expiry month is invalid.",
  ERROR_MSG_PAYMENT_PROCESS: "An error occurred while process your payment.",
  ERROR_MSG_PAYMENT_METHOD: "Payment method is not available now, try again.",
  ERROR_MSG_NO_TOKENS: "There are no saved cards",
  ERROR_MSG_NOT_RECOGNIZED: "Not recognized",
  ERROR_MSG_SUNRISE: "Something went wrong, please try again.",
  ERROR_MSG_UPDATE_CARD: "Card updation failed. Please try again.",
  ERROR_MSG_ADD_CARD: "An error occurred while adding your payment.",
  //Success messages
  SUCCESS_MSG_ADD_CARD: "Card successfully added.",
  SUCCESS_MSG_DELETE_TOKEN: "Card successfully deleted.",
  SUCCESS_MSG_UPDATE_CARD: "Card successfully updated.",
  VISA_PAYMENT_ERROR: "payment.error",
  VISA_PAYMENT_SUCCESS: "payment.success",
  VALUE_ONE: 1,
  AUTHORIZATION: "Authorization",
  CHARGE: "Charge",
  FAILURE: "Failure",
  INITIAL: "Initial",
  SUCCESS: "Success",
  DELETE: "DELETE",
  ADD_TRANSACTION: "addTransaction",
  SET_CUSTOM_FIELD: "setCustomField",
  SET_CUSTOM_TYPE: "setCustomType",
  EVENT_MESSAGE: "message",
  STRING_SET_LOCALE: "setLocale",
  //http code
  HTTP_CODE_TWO_HUNDRED_ONE: 201,
  HTTP_CODE_FOUR_HUNDRED: 400,//TODO:Paypal
  API_STATUS_CUSTOMER_AUTHENTICATION_REQUIRED: "CUSTOMER_AUTHENTICATION_REQUIRED",
  HEADER_ENCRYPTION_ALGORITHM: 'aes-256-gcm',
  UNICODE_ENCODING_SYSTEM: 'utf8',
  ENCODING_BASE_SIXTY_FOUR: 'base64',
  HEX: 'hex',
  STRING_FULLCOLON: ':',
};
